### PR TITLE
Update `paramiko` dependency.

### PR DESCRIPTION
**Pull request by bennowotny**
This removes the reported race condition behavior.

This resolves issue #26.

### CODE REVIEW

**Review by dzhao001 — COMMENTED** [review]
yep

**Comment by bennowotny** [comment]
> yep

When submitting a review, make sure to either "Approve" or "Request Changes" so that it counts towards to minimum approvals required to merge:
image

**Review by dzhao001 — APPROVED** [review]
ok

**Comment by bennowotny** [comment]
Thank you.

**Review by co-li — APPROVED** [review]

**Pull request merged**
